[book]
authors = ["Jason Ridgway-Taylor"]
language = "en"
multilingual = true
src = "src"
title = "LogKeys Parser Documentation"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/glottologist/logkeys-parser"

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
